/* Error codes */

#ifndef __ERROR_CODES__
#define __ERROR_CODES__

typedef enum
{
	ERR_OVERFLOW_OF_NUMBER_OF_ARGUMENTS = -8,
	ERR_HEAP_UNDERFLOW = -7,
	ERR_INSUFFICIENT_NUMBER_OF_ARGUMENTS = -6,
	ERR_INVALID_NUMBER_OF_ARGUMENTS = -5,
	ERR_INVALID_LENGTH_OF_SMALLER_STRING = -4,
	ERR_NULL_POINTER = -3,
	ERR_INSUFFICIENT_NUMBER_OF_KEYS_IN_BIGGER_STRING = -2,
	ERR_SMALLER_STRING_CANNOT_EXIST_IN_BIGGER_STRING = -1,
	SUCCESS = 0
} ExitCode;

#endif